name: Docs

on:
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: "experimental-features = nix-command flakes"

      - name: Build docs
        run: nix develop --command mage docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
        with:
          github_token: ${{ secrets.GOLLM_PAGES_TOKEN }}
          publish_dir: docs/public
